version: "3"

services:
  mongo:
    container_name: fitness_db
    image: mongo:latest
    ports:
      - "27017:27016"
    volumes:
      - "./mongo/db:/data/db"

  app:
    build: .
    container_name: fitness_app
    ports:
      - 3000:3000
    links:
      - "mongo:mongo"
    env_file:
      - .env.production
