version: "3.8"
services:
  mongo:
    container_name: fitness_db
    image: mongo:latest
    restart: always
    volumes:
      - "./mongo/db:/data/db"

  app:
    image: kishanlalbj/fitness-app
    ports:
      - 80:3000
    links:
      - "mongo:mongo"
    env_file:
      - .env.production
    restart: always
